use provekit_wrapper::{prove, verify};
use std::fs;
use std::path::PathBuf;

#[test]
fn test_prove_and_verify_mimc_field_1() {
    // Locate the test vectors
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let pkp_path = manifest_dir.join("test_vectors/mimc_field_1.pkp");
    let pkv_path = manifest_dir.join("test_vectors/mimc_field_1.pkv");

    // Ensure keys exist (they should be generated by the setup step)
    assert!(pkp_path.exists(), "Prover key not found at {:?}", pkp_path);
    assert!(pkv_path.exists(), "Verifier key not found at {:?}", pkv_path);

    // Prepare inputs
    // mimc_field_1.json input is "input": [Field; 1]
    // Hex string for field element is safer for TOML parser if it supports it, or integer.
    // provekit seems to use standard TOML.
    let input_toml = r#"
        input = ["123"]
    "#;

    println!("Proving with input: {}", input_toml);

    // Run Prove
    let proof_result = prove(pkp_path.to_str().unwrap(), input_toml);
    assert!(proof_result.is_ok(), "Proving failed: {:?}", proof_result.err());
    
    let proof_bytes = proof_result.unwrap();
    println!("Proof generated. Size: {} bytes", proof_bytes.len());

    // Run Verify
    let verify_result = verify(pkv_path.to_str().unwrap(), &proof_bytes);
    assert!(verify_result.is_ok(), "Verification failed: {:?}", verify_result.err());
    
    let is_valid = verify_result.unwrap();
    assert!(is_valid, "Proof verification returned false");
}
